name: Publish to npm

on:
  push:
    tags:
      - "v*" # Trigger only on tags that start with 'v', e.g., v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        working-directory: ./package
        run: npm install

      - name: Publish to npm
        working-directory: ./package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: npm publish
